# Generated by Django 2.1.2 on 2019-01-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=100)),
                ('movie_description', models.TextField()),
                ('movie_release_date', models.DateField()),
                ('movie_director', models.CharField(max_length=100)),
            ],
        ),
    ]
